# - v1.0 - Configuration
#Stores player time, last server, etc
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: estats

settings:
  # retrieves the server-name from bungeecord and uses it as part of the key {uuid, server}
  useBungeeCord: true
  # Used to force the bungee-server's name to a specific value instead of asking bungeeCord for the name
  # serverName:
  # Used to force the file location of minecraft player stats folder, usually detected automatically
  # worldFolder:
  # number of server ticks (1/20th of a second) between saving player stats, 6000 = 5 minutes
  updateInterval: 6000
  # Used to control which stats group is displayed by default
  defaultCategory: 'Player Stats'
  # Controls the output lines sent
  page-size: 18
  top: 10
  # Used to broadcast announcements across all bungee servers
  bungeecord: true

ranks:
  Initiate:
    #How we tell if they are already an initiate:
    permission: permgroup.initiate
    #requires: 'Everyone'
    objectives:
      vaturainv: 1
    announce: ''
    message: ''
    actions:
      # assign the next group with your permissions plugin
      - '/bp user @p addgroup Conscript'
      # see http://www.theredengineer.com/1.9-playsound-list.html
      - '/playsound entity.wither.death block @p @x @y @z 15 2'
      # see http://www.minecraftupdates.com/fireworks
      - '/summon FireworksRocketEntity ~ ~ ~ {LifeTime:20,FireworksItem:{id:fireworks,Count:1,tag:{Fireworks:{Explosions:[{Type:1,Flicker:0,Trail:0,Colors:[16712965],FadeColors:[16777215]}]}}}}'
      # see https://minecraftcommand.science/title-generator
      - '/title @p times 20 100 20'
      - '/title @p subtitle {"text":"You may now use /kit Conscript","color":"gray"}'
      - '/title @p title {"text":"Congratulations!","color":"aqua","bold":true}'
  Conscript:
    objectives:
    requires: Initiate
    announce: ''
    message: ''
    actions:
      - ''


objectives:
  vaturainv:
    world: vatura
    type: stat
    value: 'achievement.openInventory'
    inccomplete: '&4✘ &6Visit the surival world &fVatura&6.'
    completed: '&2✔ &6Visited the surival world &7Vatura&6.'
  playtime:
    world: all
    type: stat
    value: 'stat.playOneMinute'
    inccomplete: '&4✘ &6Time Online: &c{value}&6, needed: &f{target}&6.'
    completed: '&2✔ &6Time Online: &2{value}&6, needed: &7{target}&6.'
  blocksbroken:
    world: all
    type: aggregate
    value: 'Blocks Broken'
    inccomplete: '&4✘ &6Block Broken: &f{value}&6 of &f{target}&6.'
    completed: '&2✔ &6Block Broken: &f{value}&6 of &7{target}&6.'
  blocksplaced:
    world: all
    type: aggregate
    value: 'Blocks Placed'
    inccomplete: '&4✘ &6Block Placed: &f{value}&6 of &f{target}&6.'
    completed: '&2✔ &6Block Placed: &f{value}&6 of &7{target}&6.'


tables:
  estats_playerStats:
    category: 'Player Stats'
    playerName: true
    namespace: 'stat'
    canAggregateFields: false
    timeFields: [timeSinceDeath, sneakTime, playOneMinute]
  estats_achievement:
    category: 'Achievements'
    namespace: 'achievement'
  estats_exploredBiomes:
    category: 'Biomes Explored'
    rowAggregate: 'MAX'
    namespace: 'achievement.exploreAllBiomes.progress'
  estats_killedBy:
    category: 'Killed By MOBs'
    namespace: 'stat.entityKilledBy'
  estats_killed:
    category: 'MOBs Killed'
    namespace: 'stat.killEntity'
  estats_breakItem:
    category: 'Items Broken'
    namespace: 'stat.breakItem.minecraft'

  estats_craftBlock:
    category: 'Blocks Crafted'
    namespace: 'stat.craftItem.minecraft'
    filter: 'blocks-only'
  estats_pickupBlock:
    category: 'Blocks Picked Up'
    namespace: 'stat.pickup.minecraft'
    filter: 'blocks-only'
  estats_dropBlock:
    category: 'Blocks Dropped'
    namespace: 'stat.drop.minecraft'
    filter: 'blocks-only'
  estats_mineBlock:
    category: 'Blocks Broken'
    namespace: 'stat.mineBlock.minecraft'
  estats_placeBlock:
    category: 'Blocks Placed'
    namespace: 'stat.useItem.minecraft'
    filter: 'blocks-only'

  estats_craftItem:
    category: 'Items Crafted'
    namespace: 'stat.craftItem.minecraft'
    filter: '!blocks-only'
  estats_pickupItem:
    category: 'Items Picked Up'
    namespace: 'stat.pickup.minecraft'
    filter: '!blocks-only'
  estats_dropItem:
    category: 'Items Dropped'
    namespace: 'stat.drop.minecraft'
    filter: '!blocks-only'
  estats_useItem:
    category: 'Items Used'
    namespace: 'stat.useItem.minecraft'
    filter: '!blocks-only'

ignore:
  achievement.exploreAllBiomes: true
  #uncomment to remove warnings about unmapped stat namespaces...
  #all: true

# The following names are recognized as "blocks" for "filter: 'blocks-only'",
# for all not in this list they will match the "filter: '!blocks-only'"
# You can create as many filters as desired and they will be loaded to match
# (or not match with prefix '!') based upon the filter.
filters:
  blocks-only: [stone, grass, dirt, cobblestone, planks, sapling, bedrock, flowing_water, water, flowing_lava, lava,
  sand, gravel, gold_ore, iron_ore, coal_ore, log, log2, leaves, leaves2, sponge, glass, lapis_ore, lapis_block,
  dispenser, sandstone, noteblock, bed, golden_rail, detector_rail, sticky_piston, web, tallgrass, deadbush, piston,
  piston_head, wool, piston_extension, yellow_flower, red_flower, brown_mushroom, red_mushroom, gold_block, iron_block,
  double_stone_slab, stone_slab, brick_block, tnt, bookshelf, mossy_cobblestone, obsidian, torch, fire, mob_spawner,
  oak_stairs, chest, redstone_wire, diamond_ore, diamond_block, crafting_table, wheat, farmland, furnace, lit_furnace,
  standing_sign, wooden_door, spruce_door, birch_door, jungle_door, acacia_door, dark_oak_door, ladder, rail,
  stone_stairs, wall_sign, lever, stone_pressure_plate, iron_door, wooden_pressure_plate, redstone_ore,
  lit_redstone_ore, unlit_redstone_torch, redstone_torch, stone_button, snow_layer, ice, snow, cactus, clay, reeds,
  jukebox, fence, spruce_fence, birch_fence, jungle_fence, dark_oak_fence, acacia_fence, pumpkin, netherrack,
  soul_sand, glowstone, portal, lit_pumpkin, cake, unpowered_repeater, powered_repeater, trapdoor, monster_egg,
  stonebrick, brown_mushroom_block, red_mushroom_block, iron_bars, glass_pane, melon_block, pumpkin_stem, melon_stem,
  vine, fence_gate, spruce_fence_gate, birch_fence_gate, jungle_fence_gate, dark_oak_fence_gate, acacia_fence_gate,
  brick_stairs, stone_brick_stairs, mycelium, waterlily, nether_brick, nether_brick_fence, nether_brick_stairs,
  nether_wart, enchanting_table, brewing_stand, cauldron, end_portal, end_portal_frame, end_stone, dragon_egg,
  redstone_lamp, lit_redstone_lamp, double_wooden_slab, wooden_slab, cocoa, sandstone_stairs, emerald_ore, ender_chest,
  tripwire_hook, tripwire, emerald_block, spruce_stairs, birch_stairs, jungle_stairs, command_block, beacon,
  cobblestone_wall, flower_pot, carrots, potatoes, wooden_button, skull, anvil, trapped_chest,
  light_weighted_pressure_plate, heavy_weighted_pressure_plate, unpowered_comparator, powered_comparator,
  daylight_detector, daylight_detector_inverted, redstone_block, quartz_ore, hopper, quartz_block, quartz_stairs,
  activator_rail, dropper, stained_hardened_clay, barrier, iron_trapdoor, hay_block, carpet, hardened_clay, coal_block,
  packed_ice, acacia_stairs, dark_oak_stairs, slime, double_plant, stained_glass, stained_glass_pane, prismarine,
  sea_lantern, standing_banner, wall_banner, red_sandstone, red_sandstone_stairs, double_stone_slab2, stone_slab2,
  end_rod, chorus_plant, chorus_flower, purpur_block, purpur_pillar, purpur_stairs, purpur_double_slab, purpur_slab,
  end_bricks, beetroots, grass_path, end_gateway, repeating_command_block, chain_command_block, frosted_ice, magma,
  nether_wart_block, red_nether_brick, bone_block, structure_void, structure_block]

messages:
  no-console: '&4Command should be used by a player.'
  no-access: '&4You do not have permission to this command.'
  player-not-found: '&cPlayer not found.'
  reloaded: '&6Configuration reloaded.'
  summary-title: Category Summary
  summary-footer: '&7* use /stats {name} &7&o(Category)&r&7 for more detail'
  report-header: '&6============== [&f{title}&6] =============='
  report-line: '&6{name}: &f{value}'
  see-details: (see details)
  report-footer: '&7* Stats for user {name}&7'
  report-page-num: ' &7[Page {page} of {count}]'
  import-start: '&6Import started.'
  import-end: '&6Import completed, {count} records imported.'
  internal-error: '&cAn error occurred while processing this request.'
  category-not-found: '&cUnable to find a category by that name.'
  field-not-found: '&cUnable to find a field called ''{name}''.'
  rank-desc-format: '&6{name}: &8{desc}.'
