# - v1.0 - Configuration
#Stores player time, last server, etc
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: estats

settings:
  # retrieves the server-name from bungeecord and uses it as part of the key {uuid, server}
  useBungeeCord: true
  # Used to force the file location of minecraft player stats folder, usually detected automatically
  # worldFolder:

tables:
  estats_playerStats: 
    playerName: true
    namespace: 'stat'
  estats_achievement: 
    namespace: 'achievement'
  estats_exploredBiomes: 
    namespace: 'achievement.exploreAllBiomes.progress'
  estats_killedBy: 
    namespace: 'stat.entityKilledBy'
  estats_killed: 
    namespace: 'stat.killEntity'
  estats_breakItem: 
    namespace: 'stat.breakItem.minecraft'

  estats_craftBlock: 
    namespace: 'stat.craftItem.minecraft'
    filter: 'blocks-only'
  estats_pickupBlock: 
    namespace: 'stat.pickup.minecraft'
    filter: 'blocks-only'
  estats_dropBlock: 
    namespace: 'stat.drop.minecraft'
    filter: 'blocks-only'
  estats_mineBlock: 
    namespace: 'stat.mineBlock.minecraft'
  estats_placeBlock: 
    namespace: 'stat.useItem.minecraft'
    filter: 'blocks-only'

  estats_craftItem: 
    namespace: 'stat.craftItem.minecraft'
    filter: '!blocks-only'
  estats_pickupItem: 
    namespace: 'stat.pickup.minecraft'
    filter: '!blocks-only'
  estats_dropItem: 
    namespace: 'stat.drop.minecraft'
    filter: '!blocks-only'
  estats_useItem: 
    namespace: 'stat.useItem.minecraft'
    filter: '!blocks-only'

# The following names are recognized as "blocks" for "filter: 'blocks-only'",
# for all not in this list they will match the "filter: '!blocks-only'"
# You can create as many filters as desired and they will be loaded to match
# (or not match with prefix '!') based upon the filter.
filters:
  blocks-only: [acacia_stairs, activator_rail, anvil, beacon, birch_stairs, bookshelf, brick_block, brick_stairs,
  brown_mushroom, brown_mushroom_block, cactus, carpet, chest, clay, coal_block, coal_ore, cobblestone,
  cobblestone_wall, cocoa, command_block, crafting_table, dark_oak_stairs, daylight_detector, deadbush,
  detector_rail, diamond_block, diamond_ore, dirt, dispenser, double_plant, double_stone_slab, double_wooden_slab,
  dragon_egg, dropper, emerald_block, emerald_ore, enchanting_table, end_portal, end_portal_frame, end_stone,
  ender_chest, farmland, fence, fence_gate, furnace, glass, glass_pane, glowstone, gold_block, gold_ore, golden_rail,
  grass, gravel, hardened_clay, hay_block, heavy_weighted_pressure_plate, hopper, ice, iron_bars, iron_block,
  iron_ore, jukebox, jungle_stairs, ladder, lapis_block, lapis_ore, leaves, leaves2, lever,
  light_weighted_pressure_plate, lit_furnace, lit_pumpkin, log, log2, melon_block, monster_egg, mossy_cobblestone,
  mycelium, nether_brick, nether_brick_fence, nether_brick_stairs, netherrack, noteblock, oak_stairs, obsidian,
  packed_ice, piston, planks, portal, pumpkin, quartz_block, quartz_ore, quartz_stairs, rail, red_flower,
  red_mushroom, red_mushroom_block, redstone_block, redstone_lamp, redstone_ore, redstone_torch, sand, sandstone,
  sandstone_stairs, sapling, slime, snow, snow_layer, soul_sand, sponge, spruce_stairs, stained_glass,
  stained_glass_pane, stained_hardened_clay, sticky_piston, stone, stone_brick_stairs, stone_button,
  stone_pressure_plate, stone_slab, stone_stairs, stonebrick, tallgrass, tnt, torch, trapped_chest, tripwire_hook,
  vine, waterlily, web, wooden_button, wooden_pressure_plate, wooden_slab, wool, yellow_flower]

messages:
  no-console: '&4Command should be used by a player.'
  no-access: '&4You do not have permission to this command.'
  player-not-found: '&cPlayer not found.'
