name: EssentiallyStats
main: com.steamcraftmc.EssentiallyStats.MainPlugin
version: '1.0'
author: rknapp
load: startup
commands:
  stats:
    description: Report you or another player's current progress.
    usage: /<command> [player] [category]
    aliases: []
    permission: essentials.stats
    permission-message: 'ยง4You do not have permission to use this command.'
    default: true
  rank:
    description: Check your player's current rank progress.
    usage: /<command>
    aliases: []
    permission: essentials.rank
    permission-message: 'ยง4You do not have permission to use this command.'
    default: true
